version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
    environment:
      - DEBUG=True
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    command: python manage.py runserver 0.0.0.0:8000

  celery:
    build: .
    volumes:
      - .:/app
      - media_volume:/app/media
    environment:
      - DEBUG=True
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    command: celery -A config worker --loglevel=info

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  media_volume:
