# Generated by Django 4.2.7 on 2025-06-26 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TTSConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('text', models.TextField()),
                ('voice', models.CharField(choices=[('alloy', 'Alloy'), ('echo', 'Echo'), ('fable', 'Fable'), ('onyx', 'Onyx'), ('nova', 'Nova'), ('shimmer', 'Shimmer')], default='alloy', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('speed', models.FloatField(default=1.0)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='tts_audio/')),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tts_conversions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TTS Conversion',
                'verbose_name_plural': 'TTS Conversions',
                'ordering': ['-created_at'],
            },
        ),
    ]
