# Generated by Django 4.2.7 on 2025-06-26 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='STTConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('text', models.TextField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('model', models.CharField(choices=[('tiny', 'Tiny'), ('base', 'Base'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='base', max_length=20)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='stt_audio/')),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stt_conversions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'STT Conversion',
                'verbose_name_plural': 'STT Conversions',
                'ordering': ['-created_at'],
            },
        ),
    ]
